spring.datasource.url=jdbc:postgresql://ep-wild-brook-aeuolwz5-pooler.c-2.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_4DRUjPX9uoNJ
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Logging
logging.level.org.springframework=INFO

# App name
spring.application.name=portfolio

# Local frontend (Angular)
allowed.origins=http://localhost:4200
