spring.application.name=portfolio

# PostgreSQL (Neon) ? set these in Render env vars, but keep defaults for safety
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# CORS (Netlify)
spring.web.cors.allowed-origins=https://naveenlingala.netlify.app

# Server
server.port=8080

# JSON settings
spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false
